# Generated by Django 5.0.6 on 2024-05-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('cmail', models.TextField()),
                ('age', models.TextField()),
                ('phone', models.TextField()),
                ('male', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
